### ISSUE TITLE
Unexpected result when testing the size of a global vector

### ISSUE THREAD

**Issue by tocic** [yellowdragonlabs/TDD#1]
Consider this example:

```cpp
#include <vector>

#include "tdd.h"

const auto x = std::vector(42, 'x');

TEST(vector) {
   EXPECT(std::size(x) == 42);
}

RUN_ALL();
```

When I compile and run it with `clang++ *.cpp -std=c++20 -o t && ./t`, I get the following output:

```
main.cpp:8: error: expected (std::size(x) == 42)
1 tests, 1 errors.
```

I expect this test to pass. Are you allowed to use global variables at all? I've read the note about SIOF, does it apply here?

Also, is it possible to report a failed test's name (`vector` here) and an actual result (the result of `std::size(x)` here)?

**Comment by philtypes** [comment]
I defeated the beast called unordered dynamic initialization, after a long and arduous journey.

(C++ init is crazy.)

You can EXPECT(0) << "print". It will show file name and line number.

Thanks so much for the report.
